home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('ajax/load-tenures/', views.load_tenures, name='ajax_load_tenures'),  # <-- this one here
    path('ajax/get-principal-limits/', views.get_principal_limits, name='ajax_get_principal_limits'),  # <-- this one here
]

hook/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

from rest_framework import routers
from home import views

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

# router = routers.DefaultRouter()
# router.register(r'_users', views.UserViewSet)
# router.register(r'_groups', views.GroupViewSet)

urlpatterns = [
    # path('api/', include(router.urls)), 
    # path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    re_path(r'', include('home.urls')),
    re_path(r'^kredi/', include('loans.urls')),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^cms/', include(wagtailadmin_urls)),
    re_path(r'^documents/', include(wagtaildocs_urls)),
    re_path(r'^blog/', include(wagtail_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

# Create your models here.

loans/models.py
from django.db import models

from django.contrib import auth
from django.db.models import signals
from django.dispatch import receiver
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.contrib.postgres.fields.array import ArrayField
import uuid

"""
 ██╗      ██████╗  ██████╗ ██╗  ██╗██╗   ██╗██████╗     ████████╗ █████╗ ██████╗ ██╗     ███████╗███████╗
 ██║     ██╔═══██╗██╔═══██╗██║ ██╔╝██║   ██║██╔══██╗    ╚══██╔══╝██╔══██╗██╔══██╗██║     ██╔════╝██╔════╝
 ██║     ██║   ██║██║   ██║█████╔╝ ██║   ██║██████╔╝       ██║   ███████║██████╔╝██║     █████╗  ███████╗
 ██║     ██║   ██║██║   ██║██╔═██╗ ██║   ██║██╔═══╝        ██║   ██╔══██║██╔══██╗██║     ██╔══╝  ╚════██║
 ███████╗╚██████╔╝╚██████╔╝██║  ██╗╚██████╔╝██║            ██║   ██║  ██║██████╔╝███████╗███████╗███████║
 ╚══════╝ ╚═════╝  ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝            ╚═╝   ╚═╝  ╚═╝╚═════╝ ╚══════╝╚══════╝╚══════╝
"""

class LoanType(models.Model):
	id                 = models.UUIDField(primary_key=True, default=uuid.uuid1, editable=False)
	loan_type          = models.CharField(max_length = 3, unique = True)
	loan_type_long     = models.CharField(max_length = 100, unique = True)
	description        = models.TextField()
	active             = models.BooleanField(default=True)

	def __str__(self):
		return self.loan_type_long
		
class Principal(models.Model):
	id                   = models.UUIDField(primary_key=True, default=uuid.uuid1, editable=False)
	principal            = models.PositiveIntegerField(unique=True)
	active               = models.BooleanField(default=True)
	loan_types           = models.ManyToManyField(LoanType, related_name="principals", )

	def __str__(self):
	 return str(self.principal)

class InstallmentType(models.Model):
	id               = models.UUIDField(primary_key=True, default=uuid.uuid1, editable=False)
	installment_type = models.CharField(max_length=40,unique=True)
	active           = models.BooleanField(default=True)

	def __str__(self):
		return str(self.installment_type)

class Program(models.Model):
	id               = models.UUIDField(primary_key=True, default=uuid.uuid1, editable=False)
	program          = models.CharField(max_length=40,unique=True, default = "not_specified")
	active           = models.BooleanField(default=True)

	def __str__(self):
	 return str(self.program)

class Action(models.Model):
	id               = models.UUIDField(primary_key=True, default=uuid.uuid1, editable=False)
	action           = models.CharField(max_length=40,unique=True, default = "INSERT")
	active           = models.BooleanField(default=True)

	def __str__(self):
	 return str(self.action)

from wagtail.images.models import Image

class Bank(models.Model):
	id                 = models.UUIDField(primary_key=True, default=uuid.uuid1, editable=False)
	name               = models.CharField(max_length = 40, unique = True)
	logo               = models.ForeignKey('wagtailimages.Image',null=True,on_delete=models.SET_NULL,related_name='+')
	icon               = models.ForeignKey('wagtailimages.Image',null=True,on_delete=models.SET_NULL,related_name='+')
	slug               = models.SlugField()
	active             = models.BooleanField(default=True)

	def __str__(self):
	 return self.name

class Insurance(models.Model):
	id                = models.UUIDField(primary_key=True, default=uuid.uuid1, editable=False)
	insurance_type    = models.CharField(max_length = 40)
	description       = models.TextField()
	active            = models.BooleanField(default=True)

	def __str__(self):
	 return self.insurance_type

class Tenure(models.Model):
	id     = models.UUIDField(primary_key=True, default=uuid.uuid1, editable=False)
	tenure = models.PositiveIntegerField(unique = True)
	active = models.BooleanField(default=True)
	loan_types = models.ManyToManyField(LoanType, related_name="tenures", )

	def convert_str(self):
		if (self.tenure >= 12 and self.tenure%12==0):
			return str(self.tenure) + " ay (" +str(int(self.tenure/12))+" yıl)"
		else:
			return str(self.tenure) + " ay"
	readable_tenure = property(convert_str)

	def __str__(self):
		return str(self.tenure)
"""
 
 ██████╗ ███████╗ ██████╗ ██╗   ██╗██╗      █████╗ ██████╗     ████████╗ █████╗ ██████╗ ██╗     ███████╗███████╗
 ██╔══██╗██╔════╝██╔════╝ ██║   ██║██║     ██╔══██╗██╔══██╗    ╚══██╔══╝██╔══██╗██╔══██╗██║     ██╔════╝██╔════╝
 ██████╔╝█████╗  ██║  ███╗██║   ██║██║     ███████║██████╔╝       ██║   ███████║██████╔╝██║     █████╗  ███████╗
 ██╔══██╗██╔══╝  ██║   ██║██║   ██║██║     ██╔══██║██╔══██╗       ██║   ██╔══██║██╔══██╗██║     ██╔══╝  ╚════██║
 ██║  ██║███████╗╚██████╔╝╚██████╔╝███████╗██║  ██║██║  ██║       ██║   ██║  ██║██████╔╝███████╗███████╗███████║
 ╚═╝  ╚═╝╚══════╝ ╚═════╝  ╚═════╝ ╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝       ╚═╝   ╚═╝  ╚═╝╚═════╝ ╚══════╝╚══════╝╚══════╝
                                                                                                                
 
"""

class LoanAbs(models.Model):
	# Foreign Keys
	loan_type          = models.ForeignKey(LoanType, on_delete=models.PROTECT, db_column = 'loan_type', to_field = 'loan_type')
	bank               = models.ForeignKey(Bank, on_delete=models.PROTECT, db_column = 'bank_name', to_field= 'name')
	tenure             = models.ForeignKey(Tenure, on_delete=models.PROTECT, db_column = 'tenure', to_field = 'tenure')
	principal	       = models.ForeignKey(Principal, on_delete=models.PROTECT, db_column = 'principal', to_field= 'principal')
	# Other Fields
	name               = models.CharField(max_length = 100)
	slug               = models.SlugField()
	description        = models.TextField()
	interest           = models.FloatField()
	is_base 		   = models.BooleanField(default=False)
	is_featured        = models.BooleanField(default=False)
	feature_order      = models.PositiveIntegerField(null=True,blank=True)
	# Log Fields
	upd_user           = models.ForeignKey(auth.get_user_model(), on_delete=models.PROTECT, db_column = '_user', to_field= 'username')
	upd_program        = models.ForeignKey(Program, on_delete=models.PROTECT, db_column = '_program', to_field= 'program')
	active             = models.BooleanField(default=True)

	class Meta:
		abstract = True

class Loan(LoanAbs):
	id            	   = models.UUIDField(primary_key=True, default=uuid.uuid1, editable=False)
	upd_time           = models.DateTimeField(auto_now=True, db_column = '_upd_time')

	def save(self, *args, **kwargs):
		if self.loan_type not in self.tenure.loan_types.all():
			raise ValueError('Invalid Loan Type - Tenure combination.')
		else:
			super(Loan, self).save(*args, **kwargs)

	def __str__(self):
		return self.bank.name + "-" +str(self.loan_type) +"-"+self.name

	

class LinkAbs(models.Model):
	bank               = models.ForeignKey(Bank, on_delete=models.PROTECT, db_column = 'bank_name', to_field= 'name')
	url                = models.TextField()
	loan_type          = models.ForeignKey(LoanType, on_delete=models.CASCADE, db_column = 'loan_type', to_field = 'loan_type')
	upd_user           = models.ForeignKey(auth.get_user_model(), on_delete=models.PROTECT, db_column = '_user', to_field= 'username')
	upd_program        = models.ForeignKey(Program, on_delete=models.PROTECT, db_column = '_program', to_field= 'program')
	active             = models.BooleanField(default=True)

	class Meta:
		abstract = True

class Link(LinkAbs):
	id                 = models.UUIDField(primary_key=True, default=uuid.uuid1, editable=False)
	upd_time           = models.DateTimeField(auto_now=True, db_column = '_upd_time')

	class Meta:
		unique_together = ['loan_type', 'bank']

	def __str__(self):
		return self.bank.name+"-"+str(self.loan_type)

class LoanDetailAbs(models.Model):
	# Foreign Keys
	insurance	       = models.ForeignKey(Insurance, on_delete=models.PROTECT)
	installment_type   = models.ForeignKey(InstallmentType, on_delete=models.PROTECT)
	# Log Fields
	upd_user           = models.ForeignKey(auth.get_user_model(), on_delete=models.PROTECT, db_column = '_user', to_field= 'username')
	upd_program        = models.ForeignKey(Program, on_delete=models.PROTECT, db_column = '_program', to_field= 'program')
	active             = models.BooleanField(default=True)

	class Meta:
		abstract = True

class LoanDetail(LoanDetailAbs):
	id                 = models.UUIDField(primary_key=True, default=uuid.uuid1, editable=False)
	upd_time           = models.DateTimeField(auto_now=True, db_column = '_upd_time')
	loan               = models.OneToOneField(Loan, on_delete=models.PROTECT)

	def __str__(self):
		return str(self.loan.bank)+"-"+str(self.loan.loan_type)+"-"+self.loan.name

"""
 
 ██╗      ██████╗  ██████╗     ████████╗ █████╗ ██████╗ ██╗     ███████╗███████╗
 ██║     ██╔═══██╗██╔════╝     ╚══██╔══╝██╔══██╗██╔══██╗██║     ██╔════╝██╔════╝
 ██║     ██║   ██║██║  ███╗       ██║   ███████║██████╔╝██║     █████╗  ███████╗
 ██║     ██║   ██║██║   ██║       ██║   ██╔══██║██╔══██╗██║     ██╔══╝  ╚════██║
 ███████╗╚██████╔╝╚██████╔╝       ██║   ██║  ██║██████╔╝███████╗███████╗███████║
 ╚══════╝ ╚═════╝  ╚═════╝        ╚═╝   ╚═╝  ╚═╝╚═════╝ ╚══════╝╚══════╝╚══════╝
                                                                                
 
"""
class LoanRequest(models.Model):
	request_id   = models.UUIDField(primary_key=True, default=uuid.uuid1, editable=False)
	loan_type    = models.ForeignKey(LoanType, on_delete=models.PROTECT, db_column = 'loan_type', to_field = 'loan_type')
	tenure       = models.ForeignKey(Tenure, on_delete=models.PROTECT, db_column = 'tenure', to_field = 'tenure')
	principal    = models.PositiveIntegerField()
	request_time = models.DateTimeField(auto_now_add=True)

	@property
	def available_tenures(self):
		return self.loan_type.tenures.all()

class LoanLog(LoanAbs):
	# Log Fields
	id                 = models.UUIDField(primary_key=True,default=uuid.uuid1, editable=False)
	loan_id            = models.CharField(max_length=36)
	upd_time           = models.DateTimeField(db_column = '_upd_time')

home/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User, Group
from rest_framework import viewsets
from home.serializers import UserSerializer, GroupSerializer
from loans.models import Loan, LoanRequest, Tenure, LoanType, LoanSummary, LoanMatrixTable
from seo.models import FAQItem
from loans.forms import LoanRequestForm
from blog.models import BlogPage
from django.urls import reverse
from django.db.models import Min, Max
from datetime import date as dt
from datetime import datetime as dtm
from datetime import timedelta
from loans.views import calculate_loan_details, calculate_installment
import pprint

# Create your views here.
def index(request):
    """
    Homepage renderer function. Redirection depends on request type, otherwise will render default index page.
    << TODO: This function needs reorganization. >>
    # currently request.method == 'POST' is being redirected only to loan query page. We will change the condition to request.POST['request_type'] == xyz.
    """
    print("="*5,"SESSION","="*5)
    pprint.pprint(request.session.__dict__)
    if (request.method=='POST'):
        
        request_post = request.POST.copy()
        if request_post['request_type'] == "main_request":
            request_post['principal'] = request_post['principal'].replace(',','')
            print("=====REQUEST====")
            print(request_post)
            form = LoanRequestForm(request_post)
            if (form.is_valid()):
                form.save(loan_type=request_post['loan_type'])
                redirect_to = reverse('loan_list',
    				kwargs={
    					'principal':request_post['principal'],
    					'loan_type':request_post['loan_type'],
                        'tenure':request_post['tenure'],}
    			)
                print("redirecting to: "+redirect_to)
                return HttpResponseRedirect(redirect_to)
            else:
                return HttpResponse('form is not valid')
        elif request_post['request_type'] == "request_from_loan_summary_table":
            request_post['principal'] = request_post['principal'].replace(',','')
            print("=====REQUEST====")
            print(request_post)
            # TODO: NEW FORM CREATE & SAVE METHOD IS MISSING
            redirect_to = reverse('loan_detail_b',
                kwargs={
                    'loan_type':request_post['loan_type'],
                    'bank_slug':request_post['bank_slug'],
                    'principal':request_post['principal'],
                    'loan_type':request_post['loan_type'],
                    'tenure':request_post['tenure'],}
            )
            print("redirecting to: "+redirect_to)
            return HttpResponseRedirect(redirect_to)

    else:
        # Homepage is rendered with the code below
        blogs = BlogPage.objects.all().order_by('-date')[:4]
        faqs  = FAQItem.objects.filter(relevant_to='homepage')
        today = dt.today() if dtm.now().hour>5 else dt.today()+timedelta(days=-1)
        
        loan_summary = LoanSummary.objects.filter(date=today).order_by('-min_interest')
        loan_summary_tenures = dict(zip([e.id for e in loan_summary],[list(e.tenures.all().order_by('tenure')) for e in loan_summary]))
        loan_matrix_tables = LoanMatrixTable.objects.filter(date=today)
        featured_loans = [calculate_loan_details(e, int(e.principal.principal), int(e.tenure.tenure)) for e in Loan.objects.filter(is_featured=True).order_by('feature_order')]
        for blog in blogs:
            blog.title = blog.title if len(blog.title)<=50 else blog.title[:50]+" ..."
            blog.intro = blog.intro[:100]+" ..."
        form = LoanRequestForm()
        print(form._meta.fields)
        return render(request, 'index.html', {'form':form, 'blogs':blogs, 'faqs':faqs, 'loan_summary':loan_summary, 'loan_summary_tenures':loan_summary_tenures, 'loan_matrix_tables':loan_matrix_tables, 'featured_loans':featured_loans})

def load_tenures(request):
    """
    Filters dropdown options depending on *request*. Tenure options may be filtered according to either "slug" of the loan or "loan_type"
    << TODO: This function needs reorganization. >>
    """
    if request.GET.get('slug')==None:
        loan_type = request.GET.get('loan_type')
        print('load_tenures running with loan_type = '+ str(loan_type))
        tenures = LoanType.objects.get(loan_type=loan_type).tenures.all().exclude(tenure=0).order_by('tenure')
    else:
        tenure_ids = Loan.objects.filter(slug=request.GET.get('slug')).values_list('tenure', flat=True)
        print("tenure_ids")
        print(tenure_ids)
        tenures = Tenure.objects.filter(tenure__in=set(tenure_ids))
    limits = tenures.aggregate(Min('tenure'),Max('tenure'))
    return render(request, 'hr/tenure_dropdown_list_options.html', {'tenures': tenures, 'min': limits['tenure__min'], 'max':limits['tenure__max'], 'initial_tenure':request.GET.get('initial_tenure')})

def get_principal_limits(request):
    print('get_principal_limits running')
    if request.GET.get('slug')==None:
        principals = Loan.objects.filter(loan_type=request.GET.get('loan_type')).aggregate(Min('principal'),Max('principal'))
    else:
        principals = Loan.objects.filter(slug=request.GET.get('slug')).aggregate(Min('principal'),Max('principal'))
    return render(request, 'loans/widgets/principal_input_widget.html', {'min':str(principals['principal__min']),'max': str(principals['principal__max']), 'initial_principal':request.GET.get('initial_principal')})


class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer


class GroupViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Group.objects.all()
    serializer_class = GroupSerializer

home/templates/home/local/blog_section.html
{% load wagtailimages_tags %}
{% load static %}
<section class="features18 popup-btn-cards cid-s2gxOHzbBU" id="features18-4">
    <div class="container">
        <h2 class="mbr-section-title pb-3 align-center mbr-fonts-style display-5">GişeMemuru'ndan Haberler</h2>
        <h3 class="mbr-section-subtitle display-5 align-center mbr-fonts-style mbr-light">
            Kredinizi almadan önce bu haberleri okuyup bilgilenmenizi tavsiye ediyoruz.</h3>
        <div class="media-container-row pt-5 ">
            {% for blog in blogs %}
            <div class="card p-3 col-12 col-md-6 col-lg-3">
                <div class="card-wrapper ">
                    <div class="card-img">
                        <div class="mbr-overlay"></div>
                        <div class="mbr-section-btn text-center">
                            <a href="{{ blog.url_path }}" class="btn btn-primary display-4">Devamını oku</a>
                        </div>
                        {% image blog.cover fill-200x200-c100 alt="{{ blog.cover.alt }}" %}
                    </div>
                    <div class="card-box">
                        <a href="{{ blog.url_path }}">
                        <h4 class="card-title mbr-fonts-style display-7">
                            {{ blog.title }}
                        </h4>
                        <p class="mbr-text mbr-fonts-style align-left display-7">
                            {{ blog.intro }}
                            Devamını oku
                            <br>
                            {{ blog.date }}
                        </p>
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

home/templates/home/local/faq_section.html
{% load pandas_filters %}
<section class="toggle1 cid-s5sHqNibdR" id="toggle1-z">    
        <div class="container">
            <div class="media-container-row">
                <div class="col-12 col-md-12">
                    <div class="section-head text-center space30">
                       <h2 class="mbr-section-title pb-5 mbr-fonts-style display-5">
                            İhtiyaç kredisi ile ilgili merak edilenler
                        </h2>
                    </div>
                    <div class="clearfix"></div>
                    <div id="bootstrap-toggle" class="toggle-panel accordionStyles tab-content">
                        {% for faq in faqs %}
                        <div class="card">
                            <div class="card-header" role="tab" id="headingOne">
                                <a role="button" class="collapsed panel-title text-black" data-toggle="collapse" data-core="" href={% concat '#collapse' faq.bullet_no '_10' %}
                                aria-expanded="false" aria-controls="collapse1">
                                    <h4 class="mbr-fonts-style display-7">
                                        <span class="sign mbr-iconfont mbri-arrow-down inactive"></span> {{faq.bullet_title}}
                                    </h4>
                                </a>
                            </div>
                            <div id={% concat 'collapse' faq.bullet_no '_10' %} class="panel-collapse noScroll collapse" role="tabpanel" aria-labelledby="headingOne">
                                <div class="panel-body p-4">
                                    <p class="mbr-fonts-style panel-text display-8">
                                       {{faq.bullet_content|safe}}
                                    </p>
                                </div>
                            </div>
                        </div>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>
</section>

home/templates/home/local/featured_loan_item.html
{% load wagtailimages_tags %}
{% load pandas_filters %}
<div class="card" style="width: 16rem;">
	<div class="align-left">
		{% image loan.bank.logo fill-150x50-c100 alt="{{ loan.bank.name }}" %}<br><span class="display-7 mbr-semibold">{{ loan.name }}</span>
	</div>
  <div class="card-body">

  	<form 

        method = "post"
        id={% concat "featured_loan_" loan.slug %} 
        data-tenures-url="{% url 'ajax_load_tenures' %}"
        get-principal-limits-url="{% url 'ajax_get_principal_limits' %}">
        <input type="hidden" name="request_type" value="request_from_loan_summary_table" />
        <input type="hidden" name="loan_type" value={{ lt }} />
        <input type="hidden" name="bank_slug" value={{loan.bank.slug}} />
        
          	{% csrf_token %}
            {{ form.media }}
            <!-- principal input widget -->
            <div class="controls">
              <div class="form-group-loan-request display-8">
                  <input
                  id = {% concat "featured_loan_id_principal_" loan.slug %} 
                  name = "principal"
                  class = "form-field"
                  type = "number"
                  step = "1000"
                  min = 0
                  placeholder = "Kredi Tutarı"
                  required>
                  <span>TL</span>
              </div>
            </div>
            <div class="controls">
              <!-- tenure input widget -->
              <select 
                name="tenure" 
                class="select form-control" 
                required
                id={% concat "featured_loan_id_tenure_" loan.slug %} 
                  <option value="">Vade</option>
              </select>
            </div>
            
	</form>
    
  </div>
  <ul class="list-group list-group-flush">
    <li class="space-between">
		<span>Faiz Oranı</span>
		<span>{{ loan.interest|as_percentage }}</span>
    </li>
    <li class="space-between">
		<span>Aylık Taksit</span>
		<span>{{ loan.installment|as_currency_plain }}</span>
    </li>
    <li class="space-between">
		<span>Toplam Ödeme</span>
		<span>{{ loan.total_payment|as_currency_plain }}</span>
    </li>
    <li class="space-between">
		<button class="general-button apply-button display-7" style="background-color: green;">Hemen Başvur<span class="mobi-mbri-cursor-click "></span></button>
    </li>
  </ul>
</div>

home/templates/home/local/featured_loans_section.html
{% load wagtailimages_tags %}
{% load pandas_filters %}
{% load static %}
<section class="cid-s3nMbhVkww">
	<div class="container">
	<h2 class="mbr-section-title mbr-fonts-style align-center pb-3 display-5">Öne Çıkan Krediler</h2>
      <h3 class="mbr-section-subtitle mbr-fonts-style align-center pb-5 mbr-light display-7">
            Aşağıdaki tabloda en çok tercih edilen kredilerin faiz oranları ve tutar bilgilerini görebilirsiniz.</h3>
	<div id="ft-container" class="display-7">	
		{% for loan in featured_loans %}
			{% include "home/local/featured_loan_item.html" %}
		{% endfor %}
	</div>
</div>
<div style="height: 100px;"></div>
</section>

home/templates/home/local/loan_request_section.html
{% load static %}
{% load crispy_forms_tags %}
<section class="tabs1 cid-s2gyxGxsge" id="tabs1-5">
<div class="container">
    <h2 class="mbr-white align-center pb-5 mbr-fonts-style mbr-bold display-5">
        Kredileri karşılaştır, mantıklı kararı ver!</h2>
    <div class="media-container-row">
        <div class="col-12 col-md-8">
            <ul class="nav nav-tabs" role="tablist">
                <li class="nav-item" loan-type="GPL">
                    <a class="nav-link mbr-fonts-style display-7" onclick="hideExtraCarLoanFields()" role="tab" data-toggle="tab" href="#tabs1-5_tab0">
                        <span class="mobi-mbri mobi-mbri-cash mbr-iconfont mbr-iconfont-btn"></span>
                        İhtiyaç Kredisi
                    </a>
                </li>
                <li class="nav-item" loan-type="MOR">
                    <a class="nav-link mbr-fonts-style display-7" onclick="hideExtraCarLoanFields()" role="tab" data-toggle="tab" href="#tabs1-5_tab1">
                        <span class="mobi-mbri mobi-mbri-home mbr-iconfont mbr-iconfont-btn"></span>
                        Konut Kredisi
                    </a>
                </li>
                <li class="nav-item" loan-type="CAR">
                    <a class="nav-link mbr-fonts-style display-7" onclick="showExtraCarLoanFields()" role="tab" data-toggle="tab" href="#tabs1-5_tab2">
                        <span class="mobi-mbri mobi-mbri-shopping-cart mbr-iconfont mbr-iconfont-btn"></span>
                        Taşıt Kredisi
                    </a>
                </li>
            </ul>
            <div class="tab-content">
                <div class="row">
                    <div class="col-md-12">
                        <form
                            method = "post" id="loanRequestForm"
                            data-tenures-url="{% url 'ajax_load_tenures' %}"
                            get-principal-limits-url="{% url 'ajax_get_principal_limits' %}"
                            >
                            {% csrf_token %}
                            {{ form.media }}
                            <input type="hidden" name="request_type" value="main_request" />
                            <input type="hidden" name="loan_type" id="id_loan_type" value="GPL" />
                            <div class="row mbr-fonts-style display-7" id="car-loan-extra-fields" style="display: none">
                                <div class="col-sm-2"> <!-- BURASI COK DANDIK OLDU DEGISSIN -->
                                    <input type="radio" id="0km" name="radio-group" checked>
                                    <label for="0km">0 Km</label>
                                </div>
                                <div class="col-sm-2"> <!-- BURASI COK DANDIK OLDU DEGISSIN -->
                                    <input type="radio" id="2el" name="radio-group">
                                    <label for="2el">2. El</label>
                                </div>
                            </div>
                            {{ form.principal|as_crispy_field }}
                            {{ form.tenure|as_crispy_field }}
                            <button type="submit" class="general-button mbr-fonts-style display-4 font-weight-bold">Kredileri Listele</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script> -->
<script src="{% static 'home/js/loan_request_ops.js' %}"></script>
<script>
function showExtraCarLoanFields() {
  document.getElementById("car-loan-extra-fields").style.display = "block";
}
</script>
<script>
function hideExtraCarLoanFields() {
  document.getElementById("car-loan-extra-fields").style.display = "none";
}
</script>

</section>